FROM python:3.7.3-stretch

# Working Directory

# Copy source code to working directory

# Install packages from requirements.txt
# hadolint ignore=DL3013

# Expose port 80

# Run app.py at container launch
